import { Router } from 'express';
import authRoutes from './authRoutes';
import userRoutes from './userRoutes';
import clientRoutes from './clientRoutes';
import employeeRoutes from './employeeRoutes';
import projectRoutes from './projectRoutes';
import contractRoutes from './contractRoutes';
import roleRoutes from './roleRoutes';
import departmentRoutes from './departmentRoutes';
import participationRoutes from './participationRoutes';
import dashboardRoutes from './dashboardRoutes';
import educationRoutes from './educationRoutes';
import languageRoutes from './languageRoutes';
import availabilityRoutes from './availabilityRoutes';
import cvRoutes from './cvRoutes';
import historyProjectRoutes from './historyProjectRoutes';
import publicationRoutes from './publicationRoutes';
import certificationRoutes from './certificationRoutes';
import assistantRoutes from './assistantRoutes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/clients', clientRoutes);
router.use('/employees', employeeRoutes);
router.use('/projects', projectRoutes);
router.use('/contracts', contractRoutes);
router.use('/roles', roleRoutes);
router.use('/departments', departmentRoutes);
router.use('/participations', participationRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/employees/:employeeId/education', educationRoutes);
router.use('/employees/:employeeId/languages', languageRoutes);
router.use('/employees/:employeeId/availability', availabilityRoutes);
router.use('/employees/:employeeId/history-projects', historyProjectRoutes);
router.use('/employees/:employeeId/publications', publicationRoutes);
router.use('/employees/:employeeId/certifications', certificationRoutes);
router.use('/cv', cvRoutes);
router.use('/assistant', assistantRoutes);

export default router;
